export default {
    PDETAIL_INIT: 'PDETAIL_INIT',
    PDETAIL_ADD_INIT: 'PDETAIL_ADD_INIT',
    PDETAIL_UNMOUNT: 'PDETAIL_UNMOUNT',
    PDETAIL_CATEGORY: 'PDETAIL_CATEGORY',
    PDETAIL_FILE_CHANGE: 'PDETAIL_FILE_CHANGE',
};
